<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Phln\AuthController;
use App\Http\Controllers\Phln\PaketController;
use App\Http\Controllers\Master\RateController;
use App\Http\Controllers\Master\UnorController;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\Master\DonorController;
use App\Http\Controllers\master\SatkerController;
use App\Http\Controllers\Master\SektorController;
use App\Http\Controllers\Phln\KegiatanController;
use App\Http\Controllers\Phln\PaketAwpController;
use App\Http\Controllers\Phln\PaketOwpController;
use App\Http\Controllers\Regional\CityController;
use App\Http\Controllers\Phln\DashboardController;
use App\Http\Controllers\Phln\PaketDipaController;
use App\Http\Controllers\Phln\PaketFotoController;
use App\Http\Controllers\Master\CategoryController;
use App\Http\Controllers\Master\MataUangController;
use App\Http\Controllers\Phln\KegiatanImpController;
use App\Http\Controllers\Phln\KegiatanKpiController;
use App\Http\Controllers\Master\DepartmentController;
use App\Http\Controllers\Phln\KegiatanDipaController;
use App\Http\Controllers\Phln\KegiatanExecController;
use App\Http\Controllers\Phln\PaketAlokasiController;
use App\Http\Controllers\Regional\ProvinceController;
use App\Http\Controllers\Phln\KegiatanDokumenController;
use App\Http\Controllers\Master\ManagementUnitController;
use App\Http\Controllers\Master\KategoriKinerjaController;
use App\Http\Controllers\Phln\KegiatanKpiDetailController;

Route::group(['domain' => ''], function() {
    Route::prefix('office')->name('phln.')->group(function(){
        Route::prefix('auth')->name('auth.')->group(function(){
            Route::get('',[AuthController::class, 'index'])->name('index');
            Route::post('login',[AuthController::class, 'do_login'])->name('login');
            Route::post('register',[AuthController::class, 'do_register'])->name('register');
            Route::post('forgot',[AuthController::class, 'do_forgot'])->name('forgot');
            Route::get('reset/{token}',[AuthController::class, 'reset'])->name('getreset');
            Route::post('reset',[AuthController::class, 'do_reset'])->name('reset');
        });
        Route::middleware(['auth:office'])->group(function(){
            Route::get('dashboard',[DashboardController::class, 'index'])->name('dashboard.index');
            Route::get('dashboard-profil',[DashboardController::class, 'profil'])->name('dashboard.profil');
            Route::get('dashboard-pendanaan',[DashboardController::class, 'pendanaan'])->name('dashboard.pendanaan');
            Route::get('dashboard-kinerja',[DashboardController::class, 'kinerja'])->name('dashboard.kinerja');
            Route::get('dashboard-evaluasi-kinerja',[DashboardController::class, 'evaluasi_kinerja'])->name('dashboard.evaluasi_kinerja');
            Route::resource('province', ProvinceController::class);
            Route::get('province/{province}/city', [CityController::class, 'index'])->name('city.index');
            Route::get('province/{province}/city/create', [CityController::class, 'create'])->name('city.create');
            Route::post('city/store', [CityController::class, 'store'])->name('city.store');
            Route::get('city/{province}/{city}/edit', [CityController::class, 'edit'])->name('city.edit');
            Route::patch('city/{city}/update', [CityController::class, 'update'])->name('city.update');
            Route::delete('city/{city}/delete', [CityController::class, 'destroy'])->name('city.destroy');
            Route::post('city/get', [CityController::class, 'get_list'])->name('get_city');
            Route::post('unor/get', [UnorController::class, 'get_list'])->name('get_unor');
            Route::post('satker/get', [SatkerController::class, 'get_list'])->name('get_satker');
            Route::get('kegiatan/pdf', [KegiatanController::class, 'cetak_pdf'])->name('kegiatan.pdf');
            Route::resource('kegiatan', KegiatanController::class);
            Route::resource('hibah-terencana', HibahTerencanaController::class);
            Route::get('hibah-terencana-risk', [HibahTerencanaController::class, 'risk'])->name('hibah-terencana.risk');
            Route::get('hibah-terencana-behind-schedule', [HibahTerencanaController::class, 'bs'])->name('hibah-terencana.bs');
            Route::get('hibah-terencana-on-schedule', [HibahTerencanaController::class, 'os'])->name('hibah-terencana.os');
            Route::post('hibah-terencana/sync', [HibahTerencanaController::class, 'sync'])->name('hibah-terencana.sync');
            Route::resource('hibah-langsung', HibahLangsungController::class);
            Route::get('kegiatan-risk', [KegiatanController::class, 'risk'])->name('kegiatan.risk');
            Route::get('kegiatan-behind-schedule', [KegiatanController::class, 'bs'])->name('kegiatan.bs');
            Route::get('kegiatan-on-schedule', [KegiatanController::class, 'os'])->name('kegiatan.os');
            // Route::get('kegiatan/cetak_pdf', 'Phln/KegiatanController@cetak_pdf')->name('kegiatan.pdf');
            Route::post('kegiatan/sync', [KegiatanController::class, 'sync'])->name('kegiatan.sync');
            Route::post('kegiatan/kpi/store', [KegiatanKpiController::class, 'store'])->name('kegiatan-kpi.store');
            Route::post('kegiatan/kpi/{kegiatanKpi}/show', [KegiatanKpiController::class, 'show'])->name('kegiatan-kpi.show');
            Route::delete('kegiatan/kpi/{kegiatanKpi}/destroy', [KegiatanKpiController::class, 'destroy'])->name('kegiatan-kpi.destroy');
            Route::post('kegiatan/kpi-detail/{kegiatanKpi}/create', [KegiatanKpiController::class, 'create_kpi'])->name('kegiatan-kpi-detail.create');
            Route::post('kegiatan/kpi-detail/store', [KegiatanKpiDetailController::class, 'store'])->name('kegiatan-kpi-detail.store');
            Route::post('kegiatan/kpi-detail/{kegiatanKpiDetail}/edit', [KegiatanKpiDetailController::class, 'edit'])->name('kegiatan-kpi-detail.edit');
            Route::patch('kegiatan/kpi-detail/{kegiatanKpiDetail}/update', [KegiatanKpiDetailController::class, 'update'])->name('kegiatan-kpi-detail.update');
            Route::delete('kegiatan/kpi-detail/{kegiatanKpiDetail}/destroy', [KegiatanKpiDetailController::class, 'destroy'])->name('kegiatan-kpi-detail.destroy');
            Route::resource('kegiatan-dokumen', KegiatanDokumenController::class);
            Route::post('kegiatan-dokumen/store', [KegiatanDokumenController::class, 'store'])->name('kegiatan-dokumen.store');
            Route::delete('kegiatan-dokumen/{kegiatanDokumen}/destroy', [KegiatanDokumenController::class, 'destroy'])->name('kegiatan-dokumen.destroy');
            Route::get('kegiatan-dokumen/{kegiatanDokumen}/download', [KegiatanDokumenController::class, 'download'])->name('kegiatan-dokumen.download');
            Route::get('kegiatan/{kegiatan}/penyerapan', [PenyerapanController::class, 'index'])->name('kegiatan.penyerapan');
            Route::get('kegiatan/{kegiatan}/paket', [PaketController::class, 'index'])->name('kegiatan.paket');
            Route::get('kegiatan/{kegiatan}/paket-project-brief', [PaketController::class, 'project_brief'])->name('project_brief');
            Route::get('kegiatan/{kegiatan}/paket-timeline', [PaketController::class, 'paket_timeline'])->name('paket_timeline');
            Route::get('kegiatan/{kegiatan}/paket-owp', [PaketController::class, 'paket_owp'])->name('paket_owp');
            Route::get('kegiatan/{kegiatan}/paket-awp', [PaketController::class, 'paket_awp'])->name('paket_awp');
            Route::post('kegiatan/storeExec', [KegiatanExecController::class,'store'])->name('kegiatan.storeExec');
            Route::delete('kegiatan/{kegiatanExec}/deleteExec', [KegiatanExecController::class,'destroy'])->name('kegiatan.destroyExec');
            Route::post('kegiatan/storeImp', [KegiatanImpController::class,'store'])->name('kegiatan.storeImp');
            Route::delete('kegiatan/{kegiatanImp}/deleteImp', [KegiatanImpController::class,'destroy'])->name('kegiatan.destroyImp');
            Route::prefix('penyerapan')->name('penyerapan.')->group(function(){
                Route::get('{kegiatan}/create', [PenyerapanController::class, 'create'])->name('create');
                Route::post('store', [PenyerapanController::class, 'store'])->name('store');
                Route::get('{kegiatan}/{penyerapan}/edit', [PenyerapanController::class, 'edit'])->name('edit');
                Route::patch('{penyerapan}/update', [PenyerapanController::class, 'update'])->name('update');
                Route::delete('{penyerapan}/delete', [PenyerapanController::class, 'destroy'])->name('destroy');
            });
            Route::prefix('paket')->name('paket.')->group(function(){
                Route::get('{kegiatan}/create', [PaketController::class, 'create'])->name('create');
                Route::post('store', [PaketController::class, 'store'])->name('store');
                Route::get('{kegiatan}/{paket}/edit', [PaketController::class, 'edit'])->name('edit');
                Route::patch('{paket}/update', [PaketController::class, 'update'])->name('update');
                Route::delete('{paket}/delete', [PaketController::class, 'destroy'])->name('destroy');
            });
            Route::post('paket-foto/store', [PaketFotoController::class, 'store'])->name('paket-foto.store');
            Route::delete('paket-foto/{paketFoto}/destroy', [PaketFotoController::class, 'destroy'])->name('paket-foto.destroy');
            Route::post('paket-alokasi/store', [PaketAlokasiController::class, 'store'])->name('paket-alokasi.store');
            Route::delete('paket-alokasi/{paketAlokasi}/destroy', [PaketAlokasiController::class, 'destroy'])->name('paket-alokasi.destroy');
            Route::post('paket-dipa/store', [PaketDipaController::class, 'store'])->name('paket-dipa.store');
            Route::delete('paket-dipa/{paketDipa}/destroy', [PaketDipaController::class, 'destroy'])->name('paket-dipa.destroy');
            Route::post('management-unit/store', [ManagementUnitController::class,'store'])->name('management-unit.store');
            Route::delete('management-unit/{managementUnit}/delete', [ManagementUnitController::class,'destroy'])->name('management-unit.destroy');
            Route::post('paket-awp/store', [PaketAwpController::class,'store'])->name('paket-awp.store');
            Route::post('paket-awp/update', [PaketAwpController::class,'update'])->name('paket-awp.update');
            Route::post('paket-awp/update-masalah', [PaketAwpController::class,'update_masalah'])->name('paket-awp.update_masalah');
            Route::delete('paket-awp/{paketAwp}/delete', [PaketAwpController::class,'destroy'])->name('paket-awp.destroy');
            Route::post('paket-owp/store', [PaketOwpController::class,'store'])->name('paket-owp.store');
            Route::delete('paket-owp/{paketOwp}/delete', [PaketOwpController::class,'destroy'])->name('paket-owp.destroy');
            // Route::resource('cpmu', CpmuController::class);
            // Route::resource('pmu', PmuController::class);
            // Route::resource('piu', PiuController::class);
            Route::resource('kegiatan-dipa', KegiatanDipaController::class);
            Route::resource('jenis-satker', JenisSatkerController::class);
            Route::resource('department', DepartmentController::class);
            Route::resource('workflow', WorkflowController::class);
            Route::resource('donor', DonorController::class);
            Route::resource('penarikan', PenarikanController::class);
            Route::resource('kategori-kinerja', KategoriKinerjaController::class);
            Route::resource('mata-uang', MataUangController::class);
            Route::resource('rate', RateController::class);
            Route::post('rate/get_list', [RateController::class, 'get_list'])->name('rate.get_list');
            Route::resource('user', UserController::class);
            Route::patch('user/{user}/aktif', [UserController::class, 'aktif'])->name('user.aktif');
            Route::patch('user/{user}/taktif', [UserController::class, 'taktif'])->name('user.taktif');
            Route::resource('kl-eksternal', KlEksternalController::class);
            Route::resource('exe-agen', ExeAgenController::class);
            Route::resource('imp-agen', ImpAgenController::class);
            Route::resource('sektor', SektorController::class);
            Route::resource('category', CategoryController::class);
            Route::post('category/get_sub', [CategoryController::class, 'get_sub'])->name('category.get_sub');
            // Route::resource('unor', UnorController::class);
            Route::get('department/{department}/unor', [UnorController::class, 'index'])->name('unor.index');
            Route::get('department/{department}/unor/create', [UnorController::class, 'create'])->name('unor.create');
            Route::post('unor/store', [UnorController::class, 'store'])->name('unor.store');
            Route::get('unor/{department}/{unor}/edit', [UnorController::class, 'edit'])->name('unor.edit');
            Route::patch('unor/{unor}/update', [UnorController::class, 'update'])->name('unor.update');
            Route::delete('unor/{unor}/delete', [UnorController::class, 'destroy'])->name('unor.destroy');

            Route::get('unor/{unor}/satker', [SatkerController::class, 'index'])->name('satker.index');
            Route::get('unor/{unor}/satker/create', [SatkerController::class, 'create'])->name('satker.create');
            Route::post('satker/store', [SatkerController::class, 'store'])->name('satker.store');
            Route::get('satker/{unor}/{satker}/edit', [SatkerController::class, 'edit'])->name('satker.edit');
            Route::patch('satker/{satker}/update', [SatkerController::class, 'update'])->name('satker.update');
            Route::delete('satker/{satker}/delete', [SatkerController::class, 'destroy'])->name('satker.destroy');
            Route::get('logout',[AuthController::class, 'do_logout'])->name('auth.logout');
        });
    });
});